package org.hooray.facts

import clojure.lang.Keyword
import clojure.lang.PersistentVector
import org.hooray.UniversalComparator

/**
 * Shared helpers for the facts tests, mirroring datatoad's `tests/forest_model.rs`:
 * facts are tuples of objects ordered by [UniversalComparator], generated by the same
 * deterministic LCG, and extracted from forests by walking their layers.
 *
 * Every sub-domain below is `equals ⟺ compare == 0`-consistent (single Number type,
 * cross-type values never compare equal thanks to the type discriminators), so the
 * HashSet-based model oracles agree with the tries' compare-based deduplication.
 */

internal typealias TestFact = List<Any?>

/** A deterministic pseudo-random number generator (the LCG from forest_model.rs). */
internal fun lcg(seed: Long): () -> Long {
    var state = seed * 2 + 1
    return {
        state = state * 6364136223846793005L + 1442695040888963407L
        state ushr 33
    }
}

/** Tuples of uniformly-typed terms (small Longs), from a small domain to force duplicates. */
internal fun longTuples(count: Int, arity: Int, seed: Long): List<TestFact> {
    val next = lcg(seed)
    return List(count) { List(arity) { next() % 64 } }
}

/** Tuples of mixed-type terms, exercising the comparator's type-discriminator ordering. */
internal fun mixedTuples(count: Int, arity: Int, seed: Long): List<TestFact> {
    val next = lcg(seed)
    return List(count) {
        List(arity) {
            when ((next() % 5).toInt()) {
                0 -> null
                1 -> next() % 8
                2 -> "s${next() % 8}"
                3 -> Keyword.intern("k${next() % 8}")
                else -> PersistentVector.create(List((next() % 3).toInt()) { next() % 4 })
            }
        }
    }
}

internal fun forestOf(tuples: List<TestFact>): Forest {
    val arity = tuples[0].size
    val columns = List(arity) { Terms() }
    for (tuple in tuples) {
        require(tuple.size == arity)
        for ((col, term) in tuple.withIndex()) columns[col].pushItem(term)
    }
    return Forest.fromColumns(columns)!!
}

/** Extracts the facts of a forest by walking its layers. */
internal fun extract(forest: Forest): Set<TestFact> {
    var paths = listOf(Pair(emptyList<Any?>(), 0))
    for (layerIndex in 0 until forest.arity) {
        val layer = forest.layer(layerIndex)
        val next = ArrayList<Pair<TestFact, Int>>()
        for ((prefix, list) in paths) {
            for (item in layer.listLower(list) until layer.listUpper(list)) {
                next.add(Pair(prefix + listOf(layer.values[item]), item))
            }
        }
        paths = next
    }
    val facts = paths.map { it.first }.toSet()
    check(facts.size == forest.len()) {
        "forest len (${forest.len()}) disagrees with its distinct facts (${facts.size})"
    }
    return facts
}

internal fun extractLsm(lsm: FactLSM): Set<TestFact> =
    lsm.flatten()?.let { extract(it) } ?: emptySet()

/** The lists of a layer, each a list of items. */
internal fun layerToLists(layer: Layer): List<List<Any?>> =
    (0 until layer.size).map { list ->
        (layer.listLower(list) until layer.listUpper(list)).map { item ->
            layer.values[item]
        }
    }

/** The kernels' term order, widened to a nullable comparator for test oracles. */
internal val termOrder: Comparator<Any?> = Comparator { a, b -> UniversalComparator.compare(a, b) }
