package org.hooray.facts

/**
 * Shared helpers for the facts tests, mirroring datatoad's `tests/forest_model.rs`:
 * facts are `List<List<Int>>` (terms as unsigned-byte lists), generated by the same
 * deterministic LCG, and extracted from forests by walking their layers.
 */

internal typealias TestFact = List<List<Int>>

/** A deterministic pseudo-random number generator (the LCG from forest_model.rs). */
internal fun lcg(seed: Long): () -> Long {
    var state = seed * 2 + 1
    return {
        state = state * 6364136223846793005L + 1442695040888963407L
        state ushr 33
    }
}

internal fun bytesToInts(bytes: ByteArray): List<Int> = bytes.map { it.toInt() and 0xFF }

internal fun intsToBytes(ints: List<Int>): ByteArray = ByteArray(ints.size) { ints[it].toByte() }

/** Tuples of uniformly four-byte terms, from a small domain to force duplicates. */
internal fun fixedTuples(count: Int, arity: Int, seed: Long): List<TestFact> {
    val next = lcg(seed)
    return List(count) { List(arity) { listOf(0, 0, 0, (next() % 64).toInt()) } }
}

/** Tuples of mixed-width terms (lengths zero through four), from a small domain. */
internal fun mixedTuples(count: Int, arity: Int, seed: Long): List<TestFact> {
    val next = lcg(seed)
    return List(count) {
        List(arity) {
            val len = (next() % 5).toInt()
            List(len) { (next() % 4).toInt() }
        }
    }
}

internal fun forestOf(tuples: List<TestFact>): Forest {
    val arity = tuples[0].size
    val columns = List(arity) { Terms() }
    for (tuple in tuples) {
        require(tuple.size == arity)
        for ((col, term) in tuple.withIndex()) columns[col].pushItem(intsToBytes(term))
    }
    return Forest.fromColumns(columns)!!
}

/** Extracts the facts of a forest by walking its layers. */
internal fun extract(forest: Forest): Set<TestFact> {
    var paths = listOf(Pair(emptyList<List<Int>>(), 0))
    for (layerIndex in 0 until forest.arity) {
        val layer = forest.layer(layerIndex)
        val next = ArrayList<Pair<TestFact, Int>>()
        for ((prefix, list) in paths) {
            for (item in layer.listLower(list) until layer.listUpper(list)) {
                next.add(Pair(prefix + listOf(bytesToInts(layer.values.itemToByteArray(item))), item))
            }
        }
        paths = next
    }
    val facts = paths.map { it.first }.toSet()
    check(facts.size == forest.len()) {
        "forest len (${forest.len()}) disagrees with its distinct facts (${facts.size})"
    }
    return facts
}

internal fun extractLsm(lsm: FactLSM): Set<TestFact> =
    lsm.flatten()?.let { extract(it) } ?: emptySet()

/** The lists of a layer, each a list of items, each a list of unsigned bytes. */
internal fun layerToLists(layer: Layer): List<List<List<Int>>> =
    (0 until layer.size).map { list ->
        (layer.listLower(list) until layer.listUpper(list)).map { item ->
            bytesToInts(layer.values.itemToByteArray(item))
        }
    }

/** Unsigned lexicographic order on terms represented as Int lists. */
internal val termOrder: Comparator<List<Int>> = Comparator { a, b ->
    val shared = minOf(a.size, b.size)
    for (i in 0 until shared) {
        val cmp = a[i].compareTo(b[i])
        if (cmp != 0) return@Comparator cmp
    }
    a.size.compareTo(b.size)
}
